[phases.setup]
nixPkgs = ["curl", "ffmpeg", "python3"]

[phases.install]
cmds = [
  "npm install",
  "mkdir -p ./bin",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./bin/yt-dlp",
  "chmod +x ./bin/yt-dlp",
  "./bin/yt-dlp --version"
]

[start]
cmd = "PATH=$PATH:./bin node server.js"
